version: '2'

services:
  mysqlserver:
    image: mysql/mysql-server:5.7
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    network_mode: bridge
    restart: always
    labels:
    - traefik.enable=false

  biserver:
    image: zhicwu/biserver-ce${BI_IMAGE_TAG}
    hostname: ${SERVER_HOST}
    container_name: ${BI_CONTAINER_NAME}
    command: biserver
    ports:
      - "${SERVER_PROM_PORT}:1234"
      - "${SERVER_HTTP_PORT}:8080"
      - "${SERVER_AJP_PORT}:8009"
    volumes:
      - ./ext:/bi-ext:ro
      - ./data/.pentaho:/biserver-ce/.pentaho:rw
      - ./data/hsqldb:/biserver-ce/data/hsqldb:rw
      - ./data/logs:/biserver-ce/tomcat/logs:rw
      - ./data/repository:/biserver-ce/pentaho-solutions/system/jackrabbit/repository:rw
      - ./data/tmp:/biserver-ce/tmp:rw
      - ./database.env:/biserver-ce/database.env:ro
    environment:
      APPLY_PATCHES: Y
      BI_JAVA_OPTS: '${BI_JAVA_OPTS}'
      HOST_USER_ID: ${HOST_USER_ID}
      STORAGE_TYPE: ${STORAGE_TYPE}
      PDI_HADOOP_CONFIG: ${PDI_HADOOP_CONFIG}
      PDI_MAX_LOG_LINES: ${PDI_MAX_LOG_LINES}
      PDI_MAX_LOG_TIMEOUT: ${PDI_MAX_LOG_TIMEOUT}
      PDI_MAX_OBJ_TIMEOUT: ${PDI_MAX_OBJ_TIMEOUT}
      SERVER_NAME: ${SERVER_NAME}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_EXT_PORT}
    # still need below even using docker engine 1.12
    # see more at https://github.com/docker/docker/issues/21051 and https://docs.docker.com/engine/security/seccomp/
    security_opt:
      - seccomp:unconfined
    # https://fabiokung.com/2014/03/13/memory-inside-linux-containers/
    #mem_limit: 5000M
    #memswap_limit: 5000M
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    network_mode: bridge
    restart: always
    depends_on:
      - mysqlserver
    links:
      - mysqlserver:mysqlserver
    external_links:
      - postgreststarterkit_db_1:db
    labels:
    - traefik.backend=analytics
    - traefik.frontend.rule=Host:analytics.bieccamvd.com
    - traefik.docker.network=bridge
    - traefik.port=8080